version: '3.8'

services:
    api:
        build:
            context: ./src
            dockerfile: Dockerfile
        entrypoint: ["/app/entrypoint.sh"]
        volumes:
            - ./src/.:/app/.
            - ./logs/.:/logs/.
        ports:
            - 8000:5000
        environment:
            - FLASK_ENV=development
            - APP_SETTINGS=api.configurations.DevelopmentConfiguration
            - DATABASE_URL=postgresql://postgres:postgres@api-database:5432/api_dev
            - DATABASE_TEST_URL=postgresql://postgres:postgres@api-database:5432/api_test
        depends_on:
            - api-database

    api-database:
        build:
            context: ./database
            dockerfile: Dockerfile
        ports:
            - 8453:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres