version: '3.8'

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        entrypoint: ['/usr/src/app/entrypoint.sh']
        volumes:
            - ./src/main/resources/.:/usr/src/app
        ports:
            - 8888:8888
        environment:
            - FLASK_ENV=development
            - APP_SETTINGS=src.config.DevelopmentConfig
            - DATABASE_URL=postgresql://postgres:postgres@api-db:5432/api_dev
            - DATABASE_TEST_URL=postgresql://postgres:postgres@api-db:5432/api_test
        depends_on:
            - api-db

    api-db:
        build:
            context: ./src/db
            dockerfile: Dockerfile
        expose:
            - 5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres