services:
  athena:
    image: invictus/athena:1.0.0-SNAPSHOT
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: athena
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - APP_ENV=development
      - MYSQL_HOST=database
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=athena
    command: poetry run uvicorn athena.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./athena/core/:/athena/core/
      - ./athena/middleware/:/athena/middleware/
      - ./athena/public/:/athena/public/
      - ./athena/v1/:/athena/v1/
      - ./athena/__init__.py:/athena/__init__.py
      - ./athena/logging.cfg:/athena/logging.cfg
      - ./athena/main.py:/athena/main.py
    depends_on:
      mysql:
        condition: service_healthy


  mysql:
    image: mysql:8.1.0
    container_name: database
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=athena
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
